name: check code style

on:
  push:
    branches:
      - '!main'
      
  pull_request:
    branches:
      - main

jobs:
  code-style:
    name: Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv install --dev --deploy

      - name: Flake8
        run: pipenv run flake8 ./

      - name: Isort
        run: pipenv run isort ./ --check

      - name: Black
        run: pipenv run black ./ --check
