name: checks

on:
  push:
    branches:
      - '**'
      - '!main'
      
  pull_request:
    branches:
      - main

jobs:
  requirements:
    runs-on: ubuntu-latest
    name: Check requirements
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set checks as executable
        run: chmod +x ./checks/*.sh

      - name: Install dependencies
        id: install-dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv install --dev --deploy

      - name: Check requirements
        run: ./checks/dependencies.sh
  static:
    name: Check static Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set checks as executable
        run: chmod +x ./checks/*.sh

      - name: Install dependencies
        id: install-dependencies
        run: |
          npm ci

      - name: Check static
        run: ./checks/static.sh
  code-style:
    name: Check code Style
    runs-on: ubuntu-latest
    needs: requirements
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv install --dev --deploy

      - name: Flake8
        run: pipenv run flake8 ./

      - name: Isort
        run: pipenv run isort ./ --check

      - name: Black
        run: pipenv run black ./ --check
  migrations:
    name: Check migrations
    runs-on: ubuntu-latest
    needs: requirements
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 3306:3306
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set checks as executable
        run: chmod +x ./checks/*.sh

      - name: Install dependencies
        id: install-dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv install --dev --deploy

      - name: Check migrations
        run: ./checks/migrations.sh
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_ROOT_HOST: '%'
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
